### ISSUE TITLE
Any Login Page?

### ISSUE THREAD

**Issue by Martin-Pitt** [maxchehab/CSS-Keylogging#1]
Haven't been able to replicate it on many other login pages.

Seems this only works with very few websites out there, specifically those that for some reason have javascript setting the `value` attribute after reading it from the password input.

Probably specifically affects login pages built with React, considering its' _controlled components_?

**Comment by maxchehab** [comment]
@Martin-Pitt can you provide a login page where this doesn't work?

**Comment by michelmattos** [comment]
Maybe it only works for sites that allows CORS (`Access-Control-Allow-Origin: *`)

**Comment by StephenLynx** [comment]
Can confirm what OP is saying.
The value attribute isn't updated when you just type on a regular field.

**Comment by maxchehab** [comment]
@Martin-Pitt  @StephenLynx Understood. I will update the README.md

**Comment by JawsomeJason** [comment]
Agree. CSS does not automatically re-read non-JS-controlled values, so attribute selectors do not update.

**Comment by chadoh** [comment]
Adding an explanation to the readme of _why_ it only works with controlled components would be nice.
