### ISSUE TITLE
Keylogging on yarn server stops after space character

### ISSUE THREAD

**Issue by leophys** [maxchehab/CSS-Keylogging#5]
## Description
If the password contains a space, the server stops logging after it, displaying as last character the `+` (as expected).
## Steps to reproduce
- Follow the README
- Open instagram.com
- start keylogging
- type "test test"
### Result
`test+`
### Expected result
`test+test`

Anyway, very nice trick.

**Comment by maxchehab** [comment]
This is due to browser caching. The browser caches all requests to build the word `test` so when you type again, it  no longer sends a request.
